
package com.xtesoft.webservices.clients.clientsample;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceTest", targetNamespace = "http://ejemplowebserviceintellijidea.samples.webservice.ufg.edu.sv/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceTest {


    /**
     * 
     * @param apodo
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "test", targetNamespace = "http://ejemplowebserviceintellijidea.samples.webservice.ufg.edu.sv/", className = "com.xtesoft.webservices.clients.clientsample.Test")
    @ResponseWrapper(localName = "testResponse", targetNamespace = "http://ejemplowebserviceintellijidea.samples.webservice.ufg.edu.sv/", className = "com.xtesoft.webservices.clients.clientsample.TestResponse")
    @Action(input = "http://ejemplowebserviceintellijidea.samples.webservice.ufg.edu.sv/WebServiceTest/testRequest", output = "http://ejemplowebserviceintellijidea.samples.webservice.ufg.edu.sv/WebServiceTest/testResponse")
    public String test(
        @WebParam(name = "apodo", targetNamespace = "")
        String apodo);

}
